#!/usr/bin/env python

import os
import sys
import shutil
import glob
from pathlib import Path
import subprocess

def make_dirs(p):
    os.makedirs(p, exist_ok=True)

def copy_file(p, dest_p):
    try:
        shutil.copy2(p, dest_p, follow_symlinks=False)
    except shutil.SameFileError:
        pass

def copy_star(glob_pat, dest_p):
    for p in glob.glob(glob_pat):
        copy_file(p, dest_p)

def program_name():
    return os.path.basename(sys.argv[0])

def is_unix():
    # os.name == 'nt' for Windows
    return os.name == 'posix'

def is_macos():
    return sys.platform == 'darwin'

def main(args):
    src_files_dir = '.'
    dest_dir = '/etc/profile.d'
    copy_star(os.path.join(src_files_dir, '*.sh'), dest_dir)
    subprocess.run(['restorecon', '-vR', dest_dir], check=True)

if __name__ == '__main__':
    main(sys.argv[1:])
