#!/usr/bin/env python

import os
import sys
import shutil
import glob

def make_dirs(p):
    os.makedirs(p, exist_ok=True)

def copy_star(glob_pat, dest_p):
    for p in glob.glob(glob_pat):
        shutil.copy(p, dest_p)

def program_name():
    return os.path.basename(sys.argv[0])

def main(args):
    dot_files_dir = '.'
    try:
        (system_name,) = args
    except ValueError:
        sys.stderr.write('usage: %s fedora|mac\n' % (program_name(),))
        sys.exit(2) 

    make_dirs(os.path.expanduser('~/environments'))
    shutil.copy(os.path.join(dot_files_dir, 'inputrc'), os.path.expanduser('~/.inputrc'))
    shutil.copy(os.path.join(dot_files_dir, 'bashrc'), os.path.expanduser('~/.bashrc'))
    copy_star(os.path.join('..', system_name, 'environments', '*'),
              os.path.expanduser('~/environments'))

if __name__ == '__main__':
    main(sys.argv[1:])
