#!/usr/bin/env python

import os
import sys
import shutil
import glob
from pathlib import Path

def make_dirs(p):
    os.makedirs(p, exist_ok=True)

def copy_file(p, dest_p):
    try:
        shutil.copy2(p, dest_p, follow_symlinks=False)
    except shutil.SameFileError:
        pass

def copy_star(glob_pat, dest_p):
    for p in glob.glob(glob_pat):
        copy_file(p, dest_p)

def program_name():
    return os.path.basename(sys.argv[0])

def is_unix():
    # os.name == 'nt' for Windows
    return os.name == 'posix'

def is_macos():
    return sys.platform == 'darwin'

def main(args):
    dot_files_dir = '.'

    if is_unix():
        system_name = 'mac' if is_macos() else 'fedora'
        make_dirs(os.path.expanduser('~/environments'))
        copy_file(os.path.join(dot_files_dir, 'inputrc'), os.path.expanduser('~/.inputrc'))
        copy_file(os.path.join(dot_files_dir, 'bashrc'), os.path.expanduser('~/.bashrc'))
        copy_file(os.path.join(dot_files_dir, 'gdbinit'), os.path.expanduser('~/.gdbinit'))
        copy_file(os.path.join(dot_files_dir, 'vimrc'), os.path.expanduser('~/.vimrc'))
        copy_star(os.path.join('..', system_name, 'environments', '*'),
                os.path.expanduser('~/environments'))

    wezterm_config_dir = Path(os.path.expanduser('~/.config/wezterm'))
    wezterm_config_dir.mkdir(parents=True, exist_ok=True)
    copy_file('wezterm.lua', wezterm_config_dir / 'wezterm.lua')

    mpv_config_dir = Path(os.path.expanduser('~/.config/mpv'))
    mpv_config_dir.mkdir(parents=True, exist_ok=True)
    copy_file('mpv-input.conf', mpv_config_dir / 'input.conf')

if __name__ == '__main__':
    main(sys.argv[1:])
