#!/usr/bin/env python3

import sys
import os
import subprocess
import argparse
import pwd

import devsetup
import docker_nonroot
import user_config_files

DEBUG = 2

def main():
    parser = argparse.ArgumentParser(description='setup a macOS development machine')
    parser.add_argument('users', metavar='USER', nargs='*')
    args = parser.parse_args()

    if not args.users:
        users = [ devsetup.default_target_user() ]
    else:
        users = args.users
    uids = [ pwd.getpwnam(x).pw_uid for x in users ]

    target_arch = os.uname().machine

    if 0:
        devsetup.brew_bundle_install('dev.brew-bundle')
        devsetup.brew_bundle_install('ui.brew-bundle')
        devsetup.brew_bundle_install('com.brew-bundle')
        docker_nonroot.setup(uids[0])
    # add to /etc/shells, chsh root
    subprocess.run(['sudo', './chsh-bash'], check=True)
    # chsh normal user
    subprocess.run(['./chsh-bash'], check=True)
    user_config_files.copy()

if __name__ == '__main__':
    main()
