#!/usr/bin/env python3

import sys
import os

from devsetup import repo_and_packages_file_install

def program_name():
    return os.path.basename(sys.argv[0])

def main():
    args = sys.argv[1:]
    try:
        (filename,) = args
    except ValueError:
        sys.stderr.write('usage: %s REPO_AND_PACKAGES_FILE\n' % (program_name(),))
        sys.exit(2)

    repo_and_packages_file_install(filename, os.uname().machine)

if __name__ == '__main__':
    main()
