#!/usr/bin/env python3

import sys
import os
import subprocess
import argparse
import pwd

import devsetup
import docker_nonroot
import gnome_input_method

DEBUG = 2

def main():
    parser = argparse.ArgumentParser(description='setup a Linux development machine')
    parser.add_argument('users', metavar='USER', nargs='*')
    args = parser.parse_args()

    if not args.users:
        users = [ devsetup.default_target_user() ]
    else:
        users = args.users
    uids = [ pwd.getpwnam(x).pw_uid for x in users ]

    target_arch = os.uname().machine

    devsetup.repo_and_packages_file_install('vscode.repo-and-packages', target_arch)
    devsetup.sysctl_file_install(os.path.join('sysctl.d', '99-inotify-max-user-watches.conf'))
    devsetup.package_list_file_install('dev.packages', target_arch)
    devsetup.package_list_file_install('rpmfusion.packages', target_arch)

    if DEBUG > 1:
        print('users: %r' % (users,))
    for i in users:
        if DEBUG > 1:
            print('user: %r' % (i,), file=sys.stderr)
        docker_nonroot.setup(username=i)
        gnome_input_method.setup(target_arch, i)

    devsetup.gsettings_patch_apply('gnome-tweaks.gsettings-patch', users)
    devsetup.gsettings_patch_apply('gnome-appearance.gsettings-patch', users)
    # devsetup.gnome_custom_keybindings_apply('dev.gnome-custom-keybinding', uids)

if __name__ == '__main__':
    main()
